from fastapi import FastAPI, Request, HTTPException, BackgroundTasks                                                                                                                                                                                                                            
from fastapi.responses import HTMLResponse                                                                                                                                                                                                                                                      
from mcp.server.fastmcp import FastMCP                                                                                                                                                                                                                                                          
from mcp.server.sse import SseServerTransport                                                                                                                                                                                                                                                   
from src.health import register_health_tools                                                                                                                                                                                                                                                    
from src.docker_tools import register_docker_tools                                                                                                                                                                                                                                              
from src.vcs_tools import register_vcs_tools                                                                                                                                                                                                                                                    
from src.db.database import engine                                                                                                                                                                                                                                                              
from src.db.models import Base                                                                                                                                                                                                                                                                  
import uvicorn                                                                                                                                                                                                                                                                                  
import asyncio                                                                                                                                                                                                                                                                                  
import os                                                                                                                                                                                                                                                                                       
import json                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                
from src.agent.orchestrator import execute_agent_sweep                                                                                                                                                                                                                                          
from src.agent.scheduler import start_scheduler                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                
app = FastAPI(title="SRE Agent Control Center (Jira Mode)")                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                
# 1. Initialize and register SRE FastMCP tools                                                                                                                                                                                                                                                  
mcp = FastMCP("SRE Bug Hunter")                                                                                                                                                                                                                                                                 
register_health_tools(mcp)                                                                                                                                                                                                                                                                      
register_docker_tools(mcp)                                                                                                                                                                                                                                                                      
register_vcs_tools(mcp)                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                
# 2. Database initialization helper                                                                                                                                                                                                                                                             
async def init_db():                                                                                                                                                                                                                                                                            
    async with engine.begin() as conn:                                                                                                                                                                                                                                                          
        await conn.run_sync(Base.metadata.create_all)                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                
# 3. Startup lifecycle: run init_db and start_scheduler                                                                                                                                                                                                                                         
@app.on_event("startup")                                                                                                                                                                                                                                                                        
async def startup_event():                                                                                                                                                                                                                                                                      
    await init_db()                                                                                                                                                                                                                                                                             
    start_scheduler()                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                
# 4. Mount SRE local MCP SSE transport endpoints                                                                                                                                                                                                                                                
mcp_transport = SseServerTransport("/mcp/messages/")                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                
@app.get("/mcp/sse")                                                                                                                                                                                                                                                                            
async def handle_mcp_sse(request: Request):                                                                                                                                                                                                                                                     
    async with mcp_transport.connect_sse(                                                                                                                                                                                                                                                       
        request.scope, request.receive, request._send                                                                                                                                                                                                                                           
    ) as (in_stream, out_stream):                                                                                                                                                                                                                                                               
        await mcp._mcp_server.run(                                                                                                                                                                                                                                                              
            in_stream,                                                                                                                                                                                                                                                                          
            out_stream,                                                                                                                                                                                                                                                                         
            mcp._mcp_server.create_initialization_options()                                                                                                                                                                                                                                     
        )                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                
@app.post("/mcp/messages/")                                                                                                                                                                                                                                                                     
async def handle_mcp_messages(request: Request):                                                                                                                                                                                                                                                
    return await mcp_transport.handle_post_message(                                                                                                                                                                                                                                             
        request.scope, request.receive, request._send                                                                                                                                                                                                                                           
    )                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                
# --- 5. Jira Webhook Listener & In-Memory Event Mapping ---                                                                                                                                                                                                                                    
pending_approvals = {}  # Format: { "SRE-12": {"event": asyncio.Event(), "decision": None} }                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                
async def run_agent_command(issue_key: str, comment_body: str):
    # Clean the @SRE-Agent tag out case-insensitively
    import re
    user_command = re.sub(r"@sre-agent", "", comment_body, flags=re.IGNORECASE).strip()
    # Run the agent sweep with the specific user command context
    try:
        await execute_agent_sweep(issue_key=issue_key, user_command=user_command)
    except Exception as e:
        print(f"Error running background command for issue {issue_key}: {str(e)}")                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                
@app.post("/api/jira/webhook")                                                                                                                                                                                                                                                                  
async def handle_jira_webhook(request: Request, background_tasks: BackgroundTasks):                                                                                                                                                                                                             
    """                                                                                                                                                                                                                                                                                         
    Receives events from Jira Cloud (issue created, updated, commented, transitioned).                                                                                                                                                                                                          
    """                                                                                                                                                                                                                                                                                         
    try:                                                                                                                                                                                                                                                                                        
        body = await request.json()                                                                                                                                                                                                                                                             
    except Exception:                                                                                                                                                                                                                                                                           
        raise HTTPException(status_code=400, detail="Invalid JSON body.")                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                
    issue = body.get("issue", {})                                                                                                                                                                                                                                                               
    issue_key = issue.get("key")                                                                                                                                                                                                                                                                
    if not issue_key:                                                                                                                                                                                                                                                                           
        return {"status": "ignored", "reason": "No issue key found in payload."}                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
    event_type = body.get("webhookEvent")                                                                                                                                                                                                                                                       
    print(f"Received Jira webhook event: '{event_type}' for issue {issue_key}")                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                
    # A. Check if this is a workflow transition event                                                                                                                                                                                                                                           
    if event_type == "jira:issue_updated":                                                                                                                                                                                                                                                      
        changelog = body.get("changelog", {})                                                                                                                                                                                                                                                   
        items = changelog.get("items", [])                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                
        # Check if the "status" field was changed                                                                                                                                                                                                                                               
        for item in items:                                                                                                                                                                                                                                                                      
            if item.get("field") == "status":                                                                                                                                                                                                                                                   
                new_status = item.get("toString", "").upper()                                                                                                                                                                                                                                   
                print(f"Issue {issue_key} transitioned status to: {new_status}")                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
                # Check if we have an active agent thread waiting on this issue                                                                                                                                                                                                                 
                if issue_key in pending_approvals:                                                                                                                                                                                                                                              
                    if "APPROVE" in new_status:                                                                                                                                                                                                                                                 
                        pending_approvals[issue_key]["decision"] = "APPROVED"                                                                                                                                                                                                                   
                        pending_approvals[issue_key]["event"].set()                                                                                                                                                                                                                             
                    elif "REJECT" in new_status:                                                                                                                                                                                                                                                
                        pending_approvals[issue_key]["decision"] = "REJECTED"                                                                                                                                                                                                                   
                        pending_approvals[issue_key]["event"].set()                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                
    # B. Check if a comment command was posted (e.g. "@SRE-Agent check compliance")                                                                                                                                                                                                             
    elif event_type == "comment_created":                                                                                                                                                                                                                                                       
        comment_body = body.get("comment", {}).get("body", "")                                                                                                                                                                                                                                  
        if "@sre-agent" in comment_body.lower():                                                                                                                                                                                                                                                
            print(f"Triggering background command from comment: '{comment_body}'")                                                                                                                                                                                                              
            background_tasks.add_task(run_agent_command, issue_key, comment_body)                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                
    return {"status": "processed"}

# Simple Status landing page
@app.get("/", response_class=HTMLResponse)
async def get_root():
    return """
    <html>
        <head><title>SRE Agent</title></head>
        <body style="font-family: sans-serif; text-align: center; padding-top: 10%; background: #0f172a; color: #f1f5f9;">
            <h1>🛡️ SRE Agent Jira Webhook Listener Online</h1>
            <p style="color: #94a3b8;">Port: 8002 | Running in Jira-Native Orchestration Mode</p>
            <div style="margin-top: 20px; padding: 15px; border-radius: 8px; border: 1px solid #334155; display: inline-block; background: #1e293b;">
                <strong>Local MCP Endpoint:</strong> <code style="color: #22d3ee;">http://sre-agent:8002/mcp/sse</code>
            </div>
        </body>
    </html>
    """

if __name__ == "__main__":
    uvicorn.run("server:app", host="0.0.0.0", port=8002, reload=False)