from apscheduler.schedulers.asyncio import AsyncIOScheduler                                                                                                                                                                                                                                     
from src.agent.orchestrator import execute_agent_sweep                                                                                                                                                                                                                                          
import os                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                
scheduler = AsyncIOScheduler()                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                
def start_scheduler():                                                                                                                                                                                                                                                                          
    interval_minutes = int(os.getenv("CRON_INTERVAL_MINUTES", "30"))                                                                                                                                                                                                                            
    print(f"Scheduling SRE Agent sweep job to run every {interval_minutes} minutes...", flush=True)                                                                                                                                                                                             
    scheduler.add_job(                                                                                                                                                                                                                                                                          
        execute_agent_sweep,                                                                                                                                                                                                                                                                    
        "interval",                                                                                                                                                                                                                                                                             
        minutes=interval_minutes,                                                                                                                                                                                                                                                               
        id="sre_agent_sweep_job"                                                                                                                                                                                                                                                                
    )                                                                                                                                                                                                                                                                                           
    scheduler.start()